//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PopEdt.rc
//
#define RC_MANIFEST                     1
#define IDI_CN                          101
#define IDR_ACCELERATOR                 102
#define IDD_MENUBAR_TOOLBAR             150
#define IDD_DEVICE                      151
#define IDD_DEVICECONFIRM               152
#define IDD_BRUSH                       153
#define IDD_OBJECT                      154
#define IDD_FILTER                      155
#define IDD_DISCOVERY                   156
#define IDD_TRIGGER                     157
#define IDD_LINK                        158
#define IDD_LIST                        159
#define IDD_ABOUT                       160
#define IDD_SPELLS_BUILDINGS            161
#define IDD_SPELLS_NOT_CHARGING         162
#define IDD_ALLIES                      163
#define IDD_HEADER                      164
#define IDD_OBJ_BANK                    165
#define IDD_MAP_TYPE                    166
#define IDD_INFO                        167
#define IDD_SWAP_TRIBE                  168
#define IDD_MARKERS                     169
#define IDD_AI_ATTRIB                   170
#define IDD_AI_SCRIPT                   171
#define IDD_SCRIPT2			            182
#define ID_FILE                         300
#define ID_FILE_LEVEL_OPEN              301
#define ID_FILE_LEVEL_SAVE_AS           302
#define ID_FILE_LEVEL_SAVE              303
#define ID_FILE_LEVEL_NEW               304
#define ID_FILE_EXPORTHEIGHTMAP         305
#define ID_FILE_EXIT                    306
#define ID_EDIT                         307
#define ID_EDIT_LANDSCAPE               308
#define ID_EDIT_OBJECTS                 309
#define ID_EDIT_MARKERS                 310
#define ID_EDIT_SWAPTRIBE               311
#define ID_OPTIONS                      312
#define ID_OPTIONS_WIREFRAME_LAND       313
#define ID_OPTIONS_WIREFRAME_OBJS       314
#define ID_OPTIONS_DITHER               315
#define ID_OPTIONS_FRAMERATE            316
#define ID_OPTIONS_SHOWGRID             317
#define ID_OPTIONS_GRIDSEETHROUGH       318
#define ID_OPTIONS_SCREENMODE           319
#define ID_OPTIONS_BRUSH                320
#define ID_OPTIONS_TEXTURE_FILTER       321
#define ID_OPTIONS_MINIMAP_SHOW         322
#define ID_OPTIONS_MINIMAP_TRANSPARENT  323
#define ID_OPTIONS_MINIMAP_HIDEOBJECTS  324
#define ID_OPTIONS_OBJECTLIST           325
#define ID_OPTIONS_ABOUT                326
#define ID_OPTIONS_HIDEOBJECTS          327
#define ID_OPTIONS_BOUNDINGBOX          328
#define ID_OPTIONS_INFO                 329
#define ID_OPTIONS_SHOW_MARKERS         330
#define ID_HEADER_AVAILABLE_SPELLS_BUILDINGS 331
#define ID_HEADER_SPELLSNOTCHARGING     332
#define ID_HEADER_ALLIES                333
#define ID_HEADER_GENERAL               334
#define ID_HEADER_OBJECTBANK            335
#define ID_HEADER_MAPTEXTURE            336
#define ID_OPTIONS_HELP                 337
#define ID_AISCRIPT_ATTRIBUTES          338
#define ID_AISCRIPT_SCRIPT              339
#define ID_LANGUAGE_LANG2TEXT           340
#define ID_LANGUAGE_TEXT2LANG           341
#define IDC_MENUBAR_FILE                1001
#define IDC_MENUBAR_EDIT                1002
#define IDC_MENUBAR_OPTIONS             1003
#define IDC_MENUBAR_ABOUT               1004
#define IDC_BRUSH_SIZE                  1005
#define IDC_BRUSH_SIZE_TXT              1006
#define IDC_BRUSH_SPEED                 1007
#define IDC_BRUSH_SPEED_TXT             1008
#define IDC_BRUSH_FLATTEN               1009
#define IDC_BRUSH_SMOOTH                1010
#define IDC_OBJECT_OWNER                1011
#define IDC_OBJECT_TYPE                 1012
#define IDC_OBJECT_MODEL                1013
#define IDC_OBJECT_NEXT                 1014
#define IDC_OBJECT_PREV                 1015
#define IDC_OBJECT_FILTER               1016
#define IDC_OBJECT_OPTIONS              1017
#define IDC_OBJECT_NEW                  1018
#define IDC_OBJECT_DELETE               1019
#define IDC_OBJECT_COPY                 1020
#define IDC_FILTER_PERSON               1021
#define IDC_FILTER_BUILDING             1022
#define IDC_FILTER_UNKNOW               1023
#define IDC_FILTER_ALL                  1024
#define IDC_FILTER_NEUTRAL              1025
#define IDC_FILTER_BLUE                 1026
#define IDC_FILTER_RED                  1027
#define IDC_FILTER_GREEN                1028
#define IDC_FILTER_YELLOW               1029
#define IDC_FILTER_SCENERY              1030
#define IDC_DISCOVERY_AVAILABILITY      1031
#define IDC_DISCOVERY_TYPE              1032
#define IDC_DISCOVERY_MODEL             1033
#define IDC_DISCOVERY_MANA              1034
#define IDC_DEVICE_MODES                1035
#define IDC_DEVICE_DEVICES              1036
#define IDC_DEVICE_APPLY                1037
#define IDC_DEVICE_FULLSCREEN           1038
#define IDC_DEVICECONFIRM_TXT           1039
#define IDC_TRIGGER_TYPE                1040
#define IDC_TRIGGER_TYPE_TXT            1041
#define IDC_TRIGGER_CELLRADIUS          1042
#define IDC_TRIGGER_CELLRADIUS_TXT      1043
#define IDC_TRIGGER_OCCURENCES          1044
#define IDC_TRIGGER_OCCURENCES_TXT      1045
#define IDC_TRIGGER_COUNT               1046
#define IDC_TRIGGER_COUNT_TXT           1047
#define IDC_TRIGGER_PRAY                1048
#define IDC_TRIGGER_PRAY_TXT            1049
#define IDC_TRIGGER_INACTIVETIME        1050
#define IDC_TRIGGER_INACTIVETIME_TXT    1051
#define IDC_TRIGGER_STARTINACTIVE       1052
#define IDC_TRIGGER_CREATEOWNED         1053
#define IDC_TRIGGER_LINKS               1054
#define IDC_LINK_LIST                   1055
#define IDC_LINK_BACK                   1056
#define IDC_LINK_LINK                   1057
#define IDC_LINK_UP                     1058
#define IDC_LINK_DOWN                   1059
#define IDC_LINK_DEL                    1060
#define IDC_LIST_LIST                   1061
#define IDC_LIST_FILTER                 1062
#define IDC_FILTER_GENERAL              1063
#define IDC_FILTER_VEHICLE              1064
#define IDC_FILTER_SPELL                1065
#define IDC_FILTER_EFFECT               1066
#define IDC_ABOUT_VERSION               1067
#define IDC_ABOUT_DATE                  1068
#define IDC_ABOUT_LINK                  1069
#define IDC_SPELL_BLAST                 1070
#define IDC_SPELL_LIGHTNING             1071
#define IDC_SPELL_TORNADO               1072
#define IDC_SPELL_SWARM                 1073
#define IDC_SPELL_INVISIBILITY          1074
#define IDC_SPELL_HYPNOTISM             1075
#define IDC_SPELL_FIRESTORM             1076
#define IDC_SPELL_GHOST                 1077
#define IDC_SPELL_ERODE                 1078
#define IDC_SPELL_SWAMP                 1079
#define IDC_SPELL_LANDBRIDGE            1080
#define IDC_SPELL_AOD                   1081
#define IDC_SPELL_EARTHQUAKE            1082
#define IDC_SPELL_FLATTEN               1083
#define IDC_SPELL_VOLCANO               1084
#define IDC_SPELL_CONVERT               1085
#define IDC_SPELL_MAGICALSHIELD         1086
#define IDC_SPELLS_SPELLS               1087
#define IDC_BUILDING_HUT                1088
#define IDC_BUILDING_TOWER              1089
#define IDC_BUILDING_TEMPLE             1090
#define IDC_BUILDING_SPY                1091
#define IDC_BUILDING_WARRIOR            1092
#define IDC_BUILDING_FIREWARRIOR        1093
#define IDC_BUILDING_BOAT               1094
#define IDC_BUILDING_BALLON             1095
#define IDC_BUILDING_BUILDINGS          1096
#define IDC_ALLIES_BLUE                 1097
#define IDC_ALLIES_BLUE_BLUE            1098
#define IDC_ALLIES_BLUE_RED             1099
#define IDC_ALLIES_BLUE_YELLOW          1100
#define IDC_ALLIES_BLUE_GREEN           1101
#define IDC_ALLIES_RED                  1102
#define IDC_ALLIES_RED_BLUE             1103
#define IDC_ALLIES_RED_RED              1104
#define IDC_ALLIES_RED_YELLOW           1105
#define IDC_ALLIES_RED_GREEN            1106
#define IDC_ALLIES_YELLOW               1107
#define IDC_ALLIES_YELLOW_BLUE          1108
#define IDC_ALLIES_YELLOW_RED           1109
#define IDC_ALLIES_YELLOW_YELLOW        1110
#define IDC_ALLIES_YELLOW_GREEN         1111
#define IDC_ALLIES_GREEN                1112
#define IDC_ALLIES_GREEN_BLUE           1113
#define IDC_ALLIES_GREEN_RED            1114
#define IDC_ALLIES_GREEN_YELLOW         1115
#define IDC_ALLIES_GREEN_GREEN          1116
#define IDC_HEADER_LEVEL_NAME           1117
#define IDC_HEADER_TXT_LEVEL_NAME       1118
#define IDC_HEADER_N_PLAYERS            1119
#define IDC_HEADER_TXT_N_PLAYERS        1120
#define IDC_HEADER_GOD                  1121
#define IDC_HEADER_FOG                  1122
#define IDC_HEADER_NO_GUEST             1123
#define IDC_HEADER_CP_RED               1124
#define IDC_HEADER_TXT_CP_RED           1125
#define IDC_HEADER_CP_YELLOW            1126
#define IDC_HEADER_TXT_CP_YELLOW        1127
#define IDC_HEADER_CP_GREEN             1128
#define IDC_HEADER_TXT_CP_GREEN         1129
#define IDC_OBJ_BANK                    1130
#define IDC_MAP_TYPE                    1131
#define IDC_INFO_FILENAME               1132
#define IDC_INFO_OBJ_COUNT              1133
#define IDC_INFO_PATH                   1134
#define IDC_INFO_POP_BLUE               1135
#define IDC_INFO_POP_RED                1136
#define IDC_INFO_POP_YELLOW             1137
#define IDC_INFO_POP_GREEN              1138
#define IDC_INFO_POP_NEUTRAL            1139
#define IDC_INFO_BLG_BLUE               1140
#define IDC_INFO_BLG_RED                1141
#define IDC_INFO_BLG_YELLOW             1142
#define IDC_INFO_BLG_GREEN              1143
#define IDC_INFO_BLG_NEUTRAL            1144
#define IDC_INFO_TREE_COUNT             1145
#define IDC_INFO_WILDMAN_COUNT          1146
#define IDC_INFO_STONEHEAD_COUNT        1147
#define IDC_INFO_KNOWLEDGE_COUNT        1148
#define IDC_INFO_DISCOVERY_COUNT        1149
#define IDC_INFO_TRIGGER_COUNT          1150
#define IDC_INFO_LEVEL_NAME             1151
#define IDC_SWAPTRIBE_BLUE1             1152
#define IDC_SWAPTRIBE_RED1              1153
#define IDC_SWAPTRIBE_YELLOW1           1154
#define IDC_SWAPTRIBE_GREEN1            1155
#define IDC_SWAPTRIBE_BLUE2             1156
#define IDC_SWAPTRIBE_RED2              1157
#define IDC_SWAPTRIBE_YELLOW2           1158
#define IDC_SWAPTRIBE_GREEN2            1159
#define IDC_SWAPTRIBE_NEUTRAL1          1160
#define IDC_SWAPTRIBE_NEUTRAL2          1161
#define IDC_SWAPTRIBE_BLUE3             1162
#define IDC_SWAPTRIBE_RED3              1163
#define IDC_SWAPTRIBE_YELLOW3           1164
#define IDC_SWAPTRIBE_GREEN3            1165
#define IDC_SWAPTRIBE_NEUTRAL3          1166
#define IDC_SWAPTRIBE_BLUE4             1167
#define IDC_SWAPTRIBE_RED4              1168
#define IDC_SWAPTRIBE_YELLOW4           1169
#define IDC_SWAPTRIBE_GREEN4            1170
#define IDC_SWAPTRIBE_NEUTRAL4          1171
#define IDC_SWAPTRIBE_SWAP2             1172
#define IDC_SWAPTRIBE_SWAP              1173
#define IDC_MARKERS_NEXT                1178
#define IDC_MARKERS_PREV                1179
#define IDC_MARKERS_N                   1180
#define IDC_MARKERS_POS                 1181
#define IDC_AI_ATTRIB_LIST              1182
#define IDC_AI_ATTRIB                   1183
#define IDC_AI_CP_NAME                  1184
#define IDC_AI_NEW                      1185
#define IDC_AI_OPEN                     1186
#define IDC_AI_SAVE                     1187
#define IDC_AI_COMPILE                  1188
#define IDC_AI_DECOMPILE                1189
#define IDC_AI_EDT_LOG                  1190
#define IDC_AI_EDT_SRC                  1191
#define IDC_AI_EDT_DST                  1192
#define IDC_AI_LOG                      1193
#define IDC_AI_SRC                      1194
#define IDC_AI_DST                      1195
#define IDC_SCRIPT2                     1196
#define IDC_SCRIPT2_1                   1197
#define IDC_SCRIPT2_2                   1198
#define IDC_SCRIPT2_3                   1199
#define IDC_SCRIPT2_4                   1200
#define IDC_SCRIPT2_5                   1201
#define IDC_SCRIPT2_6                   1202
#define IDC_SCRIPT2_7                   1203
#define IDC_SCRIPT2_8                   1204
#define IDC_SCRIPT2_9                   1205
#define IDC_SCRIPT2_10                  1206
#define IDC_SCRIPT2_TXT_1               1207
#define IDC_SCRIPT2_TXT_2               1208
#define IDC_SCRIPT2_TXT_3               1209
#define IDC_SCRIPT2_TXT_4               1210
#define IDC_SCRIPT2_TXT_5               1211
#define IDC_SCRIPT2_TXT_6               1212
#define IDC_SCRIPT2_TXT_7               1213
#define IDC_SCRIPT2_TXT_8               1214
#define IDC_SCRIPT2_TXT_9               1215
#define IDC_SCRIPT2_TXT_10              1216
#define IDC_HEADER_NO_REINCARNATE_TIME  1217
#define ID_ACCEL_DLGDEVICE              40001
#define ID_ACCEL_MENUBAR                40002
#define ID_ACCEL_DLGBRUSH               40003
#define ID_ACCEL_DLGLIST                40004
#define ID_ACCEL_LAND                   40006
#define ID_ACCEL_OBJECTS                40007
#define ID_ACCEL_OPEN                   40010
#define ID_ACCEL_SAVE                   40011
#define ID_ACCEL_SAVE_AS                40012
#define ID_ACCEL_NEW                    40013
#define ID_ACCEL_HELP                   40014
#define ID_ACCEL_MARKERS                40015
#define ID_HEADER_SCRIPT2				40016
#define IDC_FILTER_SHOT                 40017
#define IDC_SWAPTRIBE_HOSTBOT1          40018
#define IDC_SWAPTRIBE_HOSTBOT2          40019
#define IDC_SWAPTRIBE_HOSTBOT3          40020
#define IDC_SWAPTRIBE_HOSTBOT4          40021
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
